name: "AWS SAM CLI Github Action"
description: "Run AWS SAM commands via Github Actions"
author: "hashtagcyber"
branding:
  icon: "terminal"
  color: "blue"
inputs:
  sam_command:
    description: "AWS SAM subcommand to execute."
    required: true
  actions_comment:
    description: "Whether or not to comment on pull requests."
    default: false
  directory:
    description: "directory in which to execute sam command."
    default: "./sam-app/"
runs:
  using: "docker"
  image: "./Dockerfile"
